include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_constructors_first: false
    sort_unnamed_constructors_first: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

formatter:
  trailing_commas: preserve
